import { VehicleBrand, VehicleModel, PartCatalogItem } from '../../models';

export const OTHER_BRAND_ID = 'other';

export const VEHICLE_BRANDS: VehicleBrand[] = [
  { id: 'toyota', name: 'Toyota' },
  { id: 'honda', name: 'Honda' },
  { id: 'nissan', name: 'Nissan' },
  { id: 'mazda', name: 'Mazda' },
  { id: 'hyundai', name: 'Hyundai' },
  { id: 'kia', name: 'Kia' },
  { id: 'mitsubishi', name: 'Mitsubishi' },
  { id: 'ford', name: 'Ford' },
  { id: 'chevrolet', name: 'Chevrolet' },
  { id: 'volkswagen', name: 'Volkswagen' },
  { id: OTHER_BRAND_ID, name: 'Otra marca' },
];

export const VEHICLE_MODELS: VehicleModel[] = [
  { id: 'toyota-corolla', brandId: 'toyota', name: 'Corolla' },
  { id: 'toyota-hilux', brandId: 'toyota', name: 'Hilux' },
  { id: 'toyota-rav4', brandId: 'toyota', name: 'RAV4' },
  { id: 'toyota-yaris', brandId: 'toyota', name: 'Yaris' },
  { id: 'honda-crv', brandId: 'honda', name: 'CR-V' },
  { id: 'honda-civic', brandId: 'honda', name: 'Civic' },
  { id: 'honda-accord', brandId: 'honda', name: 'Accord' },
  { id: 'honda-fit', brandId: 'honda', name: 'Fit' },
  { id: 'nissan-sentra', brandId: 'nissan', name: 'Sentra' },
  { id: 'nissan-frontier', brandId: 'nissan', name: 'Frontier' },
  { id: 'nissan-versa', brandId: 'nissan', name: 'Versa' },
  { id: 'mazda-3', brandId: 'mazda', name: 'Mazda 3' },
  { id: 'mazda-cx5', brandId: 'mazda', name: 'CX-5' },
  { id: 'hyundai-tucson', brandId: 'hyundai', name: 'Tucson' },
  { id: 'hyundai-accent', brandId: 'hyundai', name: 'Accent' },
  { id: 'kia-sportage', brandId: 'kia', name: 'Sportage' },
  { id: 'kia-rio', brandId: 'kia', name: 'Rio' },
  { id: 'mitsubishi-lancer', brandId: 'mitsubishi', name: 'Lancer' },
  { id: 'mitsubishi-montero', brandId: 'mitsubishi', name: 'Montero Sport' },
  { id: 'ford-ranger', brandId: 'ford', name: 'Ranger' },
  { id: 'ford-escape', brandId: 'ford', name: 'Escape' },
  { id: 'chevrolet-spark', brandId: 'chevrolet', name: 'Spark' },
  { id: 'chevrolet-dmax', brandId: 'chevrolet', name: 'D-Max' },
  { id: 'volkswagen-jetta', brandId: 'volkswagen', name: 'Jetta' },
];

export const PART_CATEGORIES = [
  'Motor', 'Frenos', 'Suspensión', 'Dirección', 'Transmisión', 'Sistema eléctrico',
  'Enfriamiento', 'Aire acondicionado', 'Filtros', 'Lubricantes', 'Carrocería',
  'Llantas', 'Mano de obra', 'Otros',
];

export const SEED_PARTS: PartCatalogItem[] = [
  { id: 'p-001', code: 'FIL-AC-001', name: 'Filtro de aceite', description: 'Filtro de aceite estándar', category: 'Filtros', compatibleBrands: ['Toyota', 'Honda'], compatibleModels: [], suggestedPrice: 55, type: 'part', active: true },
  { id: 'p-002', code: 'FIL-AI-002', name: 'Filtro de aire', description: 'Filtro de aire del motor', category: 'Filtros', compatibleBrands: ['Honda'], compatibleModels: ['CR-V'], suggestedPrice: 95, type: 'part', active: true },
  { id: 'p-003', code: 'FIL-COMB-003', name: 'Filtro de combustible', description: 'Filtro de gasolina', category: 'Filtros', compatibleBrands: [], compatibleModels: [], suggestedPrice: 85, type: 'part', active: true },
  { id: 'p-004', code: 'FIL-CAB-004', name: 'Filtro de cabina', description: 'Filtro de aire acondicionado', category: 'Aire acondicionado', compatibleBrands: [], compatibleModels: [], suggestedPrice: 120, type: 'part', active: true },
  { id: 'p-005', code: 'LUB-5W30-005', name: 'Aceite sintético 5W-30 (litro)', description: 'Aceite de motor sintético', category: 'Lubricantes', compatibleBrands: [], compatibleModels: [], suggestedPrice: 78, type: 'lubricant', active: true },
  { id: 'p-006', code: 'LUB-10W40-006', name: 'Aceite semisintético 10W-40 (litro)', description: 'Aceite de motor semisintético', category: 'Lubricantes', compatibleBrands: [], compatibleModels: [], suggestedPrice: 62, type: 'lubricant', active: true },
  { id: 'p-007', code: 'FRE-PAS-007', name: 'Pastillas de freno delanteras', description: 'Juego de pastillas cerámicas', category: 'Frenos', compatibleBrands: ['Honda'], compatibleModels: ['CR-V'], suggestedPrice: 320, type: 'part', active: true },
  { id: 'p-008', code: 'FRE-PAS-008', name: 'Pastillas de freno traseras', description: 'Juego de pastillas', category: 'Frenos', compatibleBrands: [], compatibleModels: [], suggestedPrice: 280, type: 'part', active: true },
  { id: 'p-009', code: 'FRE-DIS-009', name: 'Disco de freno delantero', description: 'Disco ventilado', category: 'Frenos', compatibleBrands: [], compatibleModels: [], suggestedPrice: 420, type: 'part', active: true },
  { id: 'p-010', code: 'FRE-LIQ-010', name: 'Líquido de frenos DOT4', description: 'Envase 500 ml', category: 'Frenos', compatibleBrands: [], compatibleModels: [], suggestedPrice: 65, type: 'material', active: true },
  { id: 'p-011', code: 'SUS-AMO-011', name: 'Amortiguador delantero', description: 'Amortiguador de gas', category: 'Suspensión', compatibleBrands: [], compatibleModels: [], suggestedPrice: 650, type: 'part', active: true },
  { id: 'p-012', code: 'SUS-AMO-012', name: 'Amortiguador trasero', description: 'Amortiguador de gas', category: 'Suspensión', compatibleBrands: [], compatibleModels: [], suggestedPrice: 590, type: 'part', active: true },
  { id: 'p-013', code: 'SUS-ROT-013', name: 'Rótula de suspensión', description: 'Rótula inferior', category: 'Suspensión', compatibleBrands: [], compatibleModels: [], suggestedPrice: 210, type: 'part', active: true },
  { id: 'p-014', code: 'DIR-TER-014', name: 'Terminal de dirección', description: 'Terminal exterior', category: 'Dirección', compatibleBrands: [], compatibleModels: [], suggestedPrice: 185, type: 'part', active: true },
  { id: 'p-015', code: 'DIR-BOM-015', name: 'Bomba de dirección hidráulica', description: 'Bomba reconstruida', category: 'Dirección', compatibleBrands: [], compatibleModels: [], suggestedPrice: 980, type: 'part', active: true },
  { id: 'p-016', code: 'TRA-ACE-016', name: 'Aceite de transmisión ATF (litro)', description: 'Fluido de transmisión automática', category: 'Transmisión', compatibleBrands: [], compatibleModels: [], suggestedPrice: 90, type: 'lubricant', active: true },
  { id: 'p-017', code: 'TRA-EMB-017', name: 'Kit de embrague', description: 'Disco, plato y collarín', category: 'Transmisión', compatibleBrands: [], compatibleModels: [], suggestedPrice: 1850, type: 'part', active: true },
  { id: 'p-018', code: 'ELE-BAT-018', name: 'Batería 12V 60Ah', description: 'Batería sellada', category: 'Sistema eléctrico', compatibleBrands: [], compatibleModels: [], suggestedPrice: 750, type: 'part', active: true },
  { id: 'p-019', code: 'ELE-BUJ-019', name: 'Bujía de encendido', description: 'Bujía de iridio (unidad)', category: 'Sistema eléctrico', compatibleBrands: [], compatibleModels: [], suggestedPrice: 68, type: 'part', active: true },
  { id: 'p-020', code: 'ELE-ALT-020', name: 'Alternador', description: 'Alternador reconstruido', category: 'Sistema eléctrico', compatibleBrands: [], compatibleModels: [], suggestedPrice: 1250, type: 'part', active: true },
  { id: 'p-021', code: 'ENF-RAD-021', name: 'Radiador', description: 'Radiador de aluminio', category: 'Enfriamiento', compatibleBrands: [], compatibleModels: [], suggestedPrice: 980, type: 'part', active: true },
  { id: 'p-022', code: 'ENF-TER-022', name: 'Termostato', description: 'Termostato con empaque', category: 'Enfriamiento', compatibleBrands: [], compatibleModels: [], suggestedPrice: 140, type: 'part', active: true },
  { id: 'p-023', code: 'ENF-REF-023', name: 'Refrigerante (galón)', description: 'Anticongelante concentrado', category: 'Enfriamiento', compatibleBrands: [], compatibleModels: [], suggestedPrice: 110, type: 'material', active: true },
  { id: 'p-024', code: 'AC-COMP-024', name: 'Compresor de A/C', description: 'Compresor reconstruido', category: 'Aire acondicionado', compatibleBrands: [], compatibleModels: [], suggestedPrice: 1650, type: 'part', active: true },
  { id: 'p-025', code: 'AC-GAS-025', name: 'Carga de gas R134a', description: 'Recarga de refrigerante', category: 'Aire acondicionado', compatibleBrands: [], compatibleModels: [], suggestedPrice: 350, type: 'material', active: true },
  { id: 'p-026', code: 'MOT-BAN-026', name: 'Banda de accesorios', description: 'Banda poly-V', category: 'Motor', compatibleBrands: [], compatibleModels: [], suggestedPrice: 165, type: 'part', active: true },
  { id: 'p-027', code: 'MOT-DIS-027', name: 'Kit de distribución', description: 'Banda, tensor y poleas', category: 'Motor', compatibleBrands: [], compatibleModels: [], suggestedPrice: 1450, type: 'part', active: true },
  { id: 'p-028', code: 'LLA-195-028', name: 'Llanta 195/65 R15', description: 'Llanta radial', category: 'Llantas', compatibleBrands: [], compatibleModels: [], suggestedPrice: 620, type: 'part', active: true },
  { id: 'p-029', code: 'CAR-PAR-029', name: 'Parachoques delantero', description: 'Bumper sin pintar', category: 'Carrocería', compatibleBrands: [], compatibleModels: [], suggestedPrice: 1100, type: 'part', active: true },
  { id: 'p-030', code: 'MO-CAMB-030', name: 'Mano de obra: cambio de aceite y filtro', description: 'Servicio de cambio de aceite', category: 'Mano de obra', compatibleBrands: [], compatibleModels: [], suggestedPrice: 120, type: 'labor', active: true },
  { id: 'p-031', code: 'MO-FRE-031', name: 'Mano de obra: cambio de frenos', description: 'Servicio por eje', category: 'Mano de obra', compatibleBrands: [], compatibleModels: [], suggestedPrice: 250, type: 'labor', active: true },
  { id: 'p-032', code: 'MO-DIAG-032', name: 'Mano de obra: diagnóstico con escáner', description: 'Diagnóstico computarizado', category: 'Mano de obra', compatibleBrands: [], compatibleModels: [], suggestedPrice: 175, type: 'labor', active: true },
  { id: 'p-033', code: 'MO-ALI-033', name: 'Mano de obra: alineación y balanceo', description: 'Servicio completo', category: 'Mano de obra', compatibleBrands: [], compatibleModels: [], suggestedPrice: 200, type: 'labor', active: true },
  { id: 'p-034', code: 'MO-SUS-034', name: 'Mano de obra: cambio de amortiguadores', description: 'Servicio por par', category: 'Mano de obra', compatibleBrands: [], compatibleModels: [], suggestedPrice: 400, type: 'labor', active: true },
];
